env:
  global:
    - CC_TEST_REPORTER_ID=4b9628bb734333de65b29ec1cda3373a9df038f75a323e5cb5fed1afc74de7cc
language: csharp
solution: AuditJournalAPI.sln  # Adjust the solution file name

mono: none
dotnet: 3.1  # Adjust the .NET Core version as needed
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - dotnet restore
  - dotnet build --configuration Release
  - dotnet test
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
