env:
  global:
    - CC_TEST_REPORTER_ID=db2bf24e3419dd2d1453db352f07e5ec1478af21d774d7220033d4869a80a907
language: csharp
solution: AuditJournalAPI.sln  # Adjust the solution file name

mono: none
dotnet: 3.1  # Adjust the .NET Core version as needed
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - dotnet restore
  - dotnet build --configuration Release
  - dotnet test
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
